#!/usr/bin/env python
from takeImage import imageCapture
from encode_image import encode_base64
from sys import argv
from webCam import image_matching
from decode_image import decode_base
from pass_encryption import pass_enc
from encrypt import encrypt_file
from decrypt import decrypt_file
import os

def check_dir():
    if os.path.exists('/home/'+os.getlogin()+'/.facelock') == False:
        os.mkdir('/home/'+os.getlogin()+'/.facelock')

def file_read():
    with open('/home/prakhar/.facelock/image','rb') as returnData:
        return returnData.read()

def rm_tmp_img():
    os.remove('/tmp/facelock.png')

if argv[1] == 'setup':
    check_dir()
    imageCapture()
    encode_base64('/tmp/facelock.png') 
    rm_tmp_img()

if argv[1] == 'encrypt':
    check_dir()
    decode_base()
    if image_matching() == True:
        encrypt_file(argv[2], pass_enc(file_read()[500:600]))
    rm_tmp_img()

if argv[1] == 'decrypt':
    check_dir()
    decode_base()
    if image_matching() == True:
        decrypt_file(argv[2], pass_enc(file_read()[500:600]))
    rm_tmp_img()
