#!/usr/bin/env python
from os import path
from os import remove
from os import mkdir
from os.path import expanduser
from sys import argv
from takeImage import imageCapture
from encode_image import encode_base64
from webCam import image_matching
from decode_image import decode_base
from pass_encryption import pass_enc
from encrypt import encrypt_file
from decrypt import decrypt_file

home = expanduser("~")
temp_image = '/tmp/facelock.png'
face_lock_image = home + '/.facelock/image'

def check_dir():
    if path.exists(face_lock_image) == False:
        mkdir(face_lock_image)

def file_read():
    with open(face_lock_image, 'rb') as returnData:
        return returnData.read()

def rm_tmp_img():
    remove(temp_image)

if argv[1] == 'setup':
    check_dir()
    imageCapture(temp_image)
    encode_base64(temp_image, face_lock_image) 
    rm_tmp_img()

if argv[1] == 'encrypt':
    check_dir()
    decode_base(temp_image, face_lock_image)
    if image_matching(temp_image) == True:
        encrypt_file(argv[2], pass_enc(file_read()[500:600]))
    rm_tmp_img()

if argv[1] == 'decrypt':
    check_dir()
    decode_base(temp_image, face_lock_image)
    if image_matching(temp_image) == True:
        decrypt_file(argv[2], pass_enc(file_read()[500:600]))
    rm_tmp_img()
